name = "base32"
description = "Simple base32 codec"
version = "1.0.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = "https://github.com/JeremyGrosser/base32"
tags = ["base32", "encoder", "decoder", "codec"]
